Laundry/Laundry/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laundry.Data;
using Laundry.Models;

namespace Laundry.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly LaundryContext _context;

        public AppointmentsController(LaundryContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Appointment.ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,PhoneNumber,Address,AppointmentDate")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                // Lưu dữ liệu vào session
                HttpContext.Session.SetString("FullName", appointment.FullName);
                HttpContext.Session.SetString("PhoneNumber", appointment.PhoneNumber);
                HttpContext.Session.SetString("Address", appointment.Address);
                HttpContext.Session.SetString("AppointmentDate", appointment.AppointmentDate.ToString());

                // Redirect đến action tiếp theo hoặc trang tiếp theo
                return RedirectToAction("Create", "LaundryItems");
            }

            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,PhoneNumber,Address,AppointmentDate")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointment.FindAsync(id);
            if (appointment != null)
            {
                _context.Appointment.Remove(appointment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointment.Any(e => e.Id == id);
        }
    }
}

Laundry/Laundry/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Laundry | Teamplate</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/slicknav.css">
    <link rel="stylesheet" href="~/assets/css/flaticon.css">
    <link rel="stylesheet" href="~/assets/css/progressbar_barfiller.css">
    <link rel="stylesheet" href="~/assets/css/gijgo.css">
    <link rel="stylesheet" href="~/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/assets/css/animated-headline.css">
    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/assets/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/css/slick.css">
    <link rel="stylesheet" href="~/assets/css/nice-select.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>
<style>
    /* CSS cho phần header */
    .header-right {
        position: relative;
    }

    .search-form {
        position: relative;
    }

        .search-form input[type="text"] {
            padding: 10px 20px;
            border: none;
            border-radius: 25px;
            background-color: #f2f2f2;
            width: 250px; 
            margin-right: 10px; 
        }

    .search-btn {
        position: absolute;
        top: 0;
        right: 0;
        width: 50px; /* Độ rộng của nút tìm kiếm */
        height: 100%;
        border: none;
        border-radius: 25px;
        background-color: #6785FF; /* Màu nền của nút tìm kiếm */
        color: #fff; /* Màu chữ của nút tìm kiếm */
        cursor: pointer;
    }

      
</style>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="~/assets/img/logo/loder.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky">
                <!-- Logo -->
                <div class="header-left">
                    <div class="logo">
                        <a asp-controller="Home" asp-action="Index"><img src="~/assets/img/logo/logo.png" alt=""></a>
                    </div>
                    <div class="menu-wrapper  d-flex align-items-center">
                        <!-- Main-menu -->
                        <div class="main-menu d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                                    <li><a asp-controller="Home" asp-action="Services">Services</a></li>
                                    <li>
                                        <ul class="submenu">
                                            <li><a href="blog.html">Blog</a></li>
                                            <li><a href="blog_details.html">Blog Details</a></li>
                                            <li><a href="elements.html">Element</a></li>
                                        </ul>
                                    </li>
                                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <!-- Search form -->
                <div class="header-right d-none d-lg-block">
                    <form asp-action="Search" asp-controller="LaundryItems" method="get" class="search-form">
                        <input type="text" name="search" id="search" placeholder="Search...">
                        <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
                    </form>
                </div>

                <div class="header-right d-none d-lg-block">
                    <a href="#" class="header-btn1"><img src="~/assets/img/icon/call.png" alt=""> (08) 728 256 266</a>
                    <a asp-controller="Appointments" asp-action="Create" class="header-btn2">Make an Appointment</a>
                </div>
                <!-- Mobile Menu -->
                <div class="col-12">
                    <div class="mobile_menu d-block d-lg-none"></div>
                </div>
            </div>
        </div>

        <!-- Header End -->
    </header>


 
            @RenderBody()



    <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo mb-35">
                                    <a href="index.html"><img src="~/assets/img/logo/logo2_footer.png" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.</p>
                                    </div>
                                </div>
                                <!-- social -->
                                <div class="footer-social">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Services </h4>
                                <ul>
                                    <li><a href="#">- Dry Cleaning</a></li>
                                    <li><a href="#">- Dry Clean</a></li>
                                    <li><a href="#">- Ironing Services</a></li>
                                    <li><a href="#">- Laundry Service London</a></li>
                                    <li><a href="#">- Laundry App</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Get in touch</h4>
                                <ul>
                                    <li class="number"><a href="#">(90) 898 789-8957</a></li>
                                    <li><a href="#">laundry@567.com</a></li>
                                    <li><a href="#">789/A, Green road NYC-9089</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- footer-bottom area -->
        <div class="footer-bottom-area section-bg2" data-background="~/assets/img/gallery/footer-bg.png">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>

    <!-- JS here -->

    <script src="~/assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/assets/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="~/assets/js/wow.min.js"></script>
    <script src="~/assets/js/animated.headline.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.js"></script>

    <!-- Date Picker -->
    <script src="~/assets/js/gijgo.min.js"></script>
    <!-- Nice-select, sticky -->
    <script src="~/assets/js/jquery.nice-select.min.js"></script>
    <script src="~/assets/js/jquery.sticky.js"></script>
    <!-- Progress -->
    <script src="~/assets/js/jquery.barfiller.js"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>
    <script src="~/assets/js/jquery.countdown.min.js"></script>
    <script src="~/assets/js/hover-direction-snake.min.js"></script>

    <!-- contact js -->
    <script src="~/assets/js/contact.js"></script>
    <script src="~/assets/js/jquery.form.js"></script>
    <script src="~/assets/js/jquery.validate.min.js"></script>
    <script src="~/assets/js/mail-script.js"></script>
    <script src="~/assets/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/main.js"></script>
</body>
</html>