Laundry/Laundry/Controllers/LaundryItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laundry.Data;
using Laundry.Models;
using Microsoft.AspNetCore.Http;

namespace Laundry.Controllers
{
    public class LaundryItemsController : Controller
    {
        private readonly LaundryContext _context;

        public LaundryItemsController(LaundryContext context)
        {
            _context = context;
        }

        // GET: LaundryItems
        public async Task<IActionResult> Index()
        {
            return View(await _context.LaundryItems.ToListAsync());
        }

        // GET: LaundryItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laundryItem = await _context.LaundryItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (laundryItem == null)
            {
                return NotFound();
            }

            return View(laundryItem);
        }

        // GET: LaundryItems/Create
        public IActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("FullName")))
            {
                return RedirectToAction("Create", "Appointments");
            }

            var laundryItems = _context.LaundryItems.ToList();
            return View(laundryItems);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string[] selectedProducts, Dictionary<string, int> quantities)
        {
            if (selectedProducts == null || selectedProducts.Length == 0)
            {
                ModelState.AddModelError(string.Empty, "Please select at least one product.");
                var laundryItems = _context.LaundryItems.ToList();
                return View(laundryItems);
            }

            var selectedProductsByteArray = selectedProducts.Select(s => int.Parse(s)).SelectMany(BitConverter.GetBytes).ToArray();

            var quantitiesByteArray = quantities.SelectMany(kv => BitConverter.GetBytes(int.Parse(kv.Key))
                                                        .Concat(BitConverter.GetBytes(kv.Value)))
                                                        .ToArray();

            HttpContext.Session.Set("SelectedProducts", selectedProductsByteArray);

            HttpContext.Session.Set("Quantities", quantitiesByteArray);

            return RedirectToAction("ReviewOrder");
        }

        public IActionResult ReviewOrder()
        {
            var fullName = HttpContext.Session.GetString("FullName");
            var phoneNumber = HttpContext.Session.GetString("PhoneNumber");
            var address = HttpContext.Session.GetString("Address");
            var appointmentDate = HttpContext.Session.GetString("AppointmentDate");

            var laundryItems = _context.LaundryItems.ToList();

            var selectedProducts = HttpContext.Session.Get("SelectedProducts");
            var quantities = HttpContext.Session.Get("Quantities");

            var selectedProductIds = new List<int>();

            if (selectedProducts != null)
            {
                for (int i = 0; i < selectedProducts.Length; i += 4)
                {
                    selectedProductIds.Add(BitConverter.ToInt32(selectedProducts, i));
                }
            }

            var totalPrice = 0m; // Tính tổng tiền từ các sản phẩm đã chọn với kiểu decimal
            var viewModel = new OrderViewModel
            {
                FullName = fullName ?? "",
                PhoneNumber = phoneNumber ?? "",
                Address = address ?? "",
                AppointmentDate = appointmentDate ?? "",
                SelectedProducts = selectedProductIds,
                Quantities = ConvertByteArrayToDictionary(quantities),
                LaundryItems = laundryItems
            };

            foreach (var selectedProductId in viewModel.SelectedProducts)
            {
                var selectedItem = viewModel.LaundryItems.FirstOrDefault(item => item.Id == selectedProductId);
                var quantity = viewModel.Quantities.ContainsKey(selectedProductId) ? viewModel.Quantities[selectedProductId] : 0;
                if (selectedItem != null)
                {
                    totalPrice += selectedItem.Price * quantity;
                }
            }

            // Gán tổng tiền vào model
            viewModel.TotalPrice = totalPrice;

            return View("~/Views/Order/ReviewOrder.cshtml", viewModel);
        }



        // Phương thức chuyển đổi từ byte array sang Dictionary<int, int>
        private Dictionary<int, int> ConvertByteArrayToDictionary(byte[] byteArray)
        {
            var quantities = new Dictionary<int, int>();

            if (byteArray != null)
            {
                for (int i = 0; i < byteArray.Length; i += 8)
                {
                    var key = BitConverter.ToInt32(byteArray, i);
                    var value = BitConverter.ToInt32(byteArray, i + 4);
                    quantities.Add(key, value);
                }
            }

            return quantities;
        }




        // GET: LaundryItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laundryItem = await _context.LaundryItems.FindAsync(id);
            if (laundryItem == null)
            {
                return NotFound();
            }
            return View(laundryItem);
        }

        // POST: LaundryItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Product,Description,Weight")] LaundryItem laundryItem)
        {
            if (id != laundryItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(laundryItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LaundryItemExists(laundryItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(laundryItem);
        }

        // GET: LaundryItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laundryItem = await _context.LaundryItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (laundryItem == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/AddProduct.cshtml", laundryItem);
        }

        // POST: LaundryItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var laundryItem = await _context.LaundryItems.FindAsync(id);
            if (laundryItem != null)
            {
                _context.LaundryItems.Remove(laundryItem);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LaundryItemExists(int id)
        {
            return _context.LaundryItems.Any(e => e.Id == id);
        }

        public IActionResult Thank()
        {
            // Get the ID of the last saved OrderDetail
            int lastOrderId = _context.OrderDetail.Max(order => order.Id);

            // Retrieve the last saved OrderDetail from the database
            var order = _context.OrderDetail
                            .Where(o => o.Id == lastOrderId)
                            .FirstOrDefault();

            return View("~/Views/Order/Thanks.cshtml", order); // Trả về một OrderDetail thay vì một danh sách
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PlaceOrder()
        {
            // Lấy thông tin từ Session
            var fullName = HttpContext.Session.GetString("FullName");
            var phoneNumber = HttpContext.Session.GetString("PhoneNumber");
            var address = HttpContext.Session.GetString("Address");
            var appointmentDate = HttpContext.Session.GetString("AppointmentDate");
            var selectedProducts = HttpContext.Session.Get("SelectedProducts");
            var quantities = HttpContext.Session.Get("Quantities");
            var totalPrice = 0m; // Khởi tạo tổng tiền

            // Tạo đối tượng OrderDetail
            var orderDetail = new OrderDetail
            {
                OrderCode = GenerateOrderCode(),
                FullName = fullName,
                PhoneNumber = phoneNumber,
                Address = address,
                AppointmentDate = appointmentDate,
                Status = OrderStatus.WaitingForDelivery
            };

            // Lặp qua danh sách các sản phẩm đã chọn để tính tổng tiền
            if (selectedProducts != null && quantities != null)
            {
                for (int i = 0; i < selectedProducts.Length; i += 4)
                {
                    var productId = BitConverter.ToInt32(selectedProducts, i);

Laundry/Laundry/Views/Order/OrderStatus.cshtml
@model List<Laundry.Models.OrderDetail>

@{
    ViewData["Title"] = "Order Status";
}

<style>
    .container1 {
        max-width: 600px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color: #4CAF50;
        font-size: 36px;
        margin-bottom: 20px;
        text-transform: uppercase;
        font-weight: bold;
        letter-spacing: 2px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
    }

    p {
        color: #555;
        margin: 5px 0;
    }

    .order-info {
        margin-top: 20px;
        padding: 15px;
        border: 1px solid #ddd;
        border-radius: 6px;
        background-color: #f9f9f9;
    }

        .order-info p {
            font-weight: bold;
        }
</style>


@if (Model != null && Model.Count > 0)
{
    @foreach (var order in Model)
    {
        <div class="container1">
            <h2>Order Status</h2>

            <div class="order-details">
                <p><strong>Order Code:</strong> @order.OrderCode</p>
                <p><strong>Full Name:</strong> @order.FullName</p>
                <p><strong>Phone Number:</strong> @order.PhoneNumber</p>
                <p><strong>Address:</strong> @order.Address</p>
                <p><strong>Appointment Date:</strong> @order.AppointmentDate</p>
                <p><strong>Product:</strong> @order.Product</p>
                <p><strong>Quantity:</strong> @order.Quantity</p>
                <p><strong>Price:</strong> $@order.Price</p>
                <p><strong>Status:</strong> @order.Status</p>
            </div>
        </div>
    }
}
else
{
    <p>No orders found.</p>
}

Laundry/Laundry/Views/Order/ReviewOrder.cshtml
@model Laundry.Controllers.OrderViewModel

<style>
    /* CSS styles here */
    .order-container {
        margin: 50px auto;
        max-width: 800px;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
    }

        .order-container h2 {
            font-size: 24px;
            color: #333;
            margin-bottom: 10px;
        }

    .customer-info,
    .appointment-info,
    .laundry-item-info {
        margin-bottom: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th,
    td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    .order-item p {
        margin: 5px 0;
    }

    .confirm-button {
        text-align: center;
    }

        .confirm-button button {
            background-color: #007bff;
            border-color: #007bff;
            padding: 10px 20px;
            border-radius: 5px;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s;
        }

            .confirm-button button:hover {
                background-color: #0056b3;
            }
</style>

<div class="order-container">
    <h1>Review Order</h1>

    <div class="customer-info">
        <h2>Customer Information</h2>
        <p><strong>Full Name:</strong> @Model.FullName</p>
        <p><strong>Phone Number:</strong> @Model.PhoneNumber</p>
        <p><strong>Address:</strong> @Model.Address</p>
    </div>

    <div class="appointment-info">
        <h2>Appointment Information</h2>
        <p><strong>Appointment Date:</strong> @Model.AppointmentDate</p>
    </div>

    <div class="laundry-item-info">
        <h2>Laundry Item Information</h2>
        @if (Model.SelectedProducts != null && Model.Quantities != null)
        {
            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var selectedProductId in Model.SelectedProducts)
                    {
                        var selectedItem = Model.LaundryItems.FirstOrDefault(item => item.Id == selectedProductId);
                        var quantity = Model.Quantities.ContainsKey(selectedProductId) ? Model.Quantities[selectedProductId] : 0;
                        if (selectedItem != null)
                        {
                            <tr>
                                <td>@selectedItem.Product</td>
                                <td>@String.Format("{0:C}", selectedItem.Price)</td>
                                <td>@quantity</td>
                            </tr>
                        }
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2"></td>
                        <td>Total:@String.Format("{0:C}", Model.TotalPrice)</td>
                    </tr>
                </tfoot>
            </table>
        }
        else
        {
            <p>No selected products.</p>
        }
    </div>

    <div class="confirm-button">
        <form asp-controller="LaundryItems" asp-action="PlaceOrder" method="post">
            <button type="submit" class="btn btn-confirm">Confirm Order</button>
        </form>
    </div>
</div>

Laundry/Laundry/Views/Order/Thanks.cshtml
@model Laundry.Models.OrderDetail

<style>
    .container1 {
        max-width: 600px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color: #4CAF50;
        font-size: 36px;
        margin-bottom: 20px;
        text-transform: uppercase;
        font-weight: bold;
        letter-spacing: 2px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
    }

    p {
        color: #555;
        margin: 5px 0;
    }

    .order-info {
        margin-top: 20px;
        padding: 15px;
        border: 1px solid #ddd;
        border-radius: 6px;
        background-color: #f9f9f9;
    }

        .order-info p {
            font-weight: bold;
        }
</style>

<div class="container1">
    <h2>Thank you for your order!</h2>

    <div class="order-info">
        <p>Order Code: @Model.OrderCode</p>
        <p>Full Name: @Model.FullName</p>
        <p>Phone Number: @Model.PhoneNumber</p>
        <p>Address: @Model.Address</p>
        <p>Appointment Date: @Model.AppointmentDate</p>
        <p>Product: @Model.Product</p>
        <p>Price: $@Model.Price</p>
        <p>Status: @Model.Status</p>
    </div>

    <p>Please remember your <strong>Order Code</strong>  to conveniently view your order</p>
</div>